openapi: 3.2.0
info:
  version: '2015-07-09'
  x-release: v4
  title: 'AWS CodePipeline #X Amz Target=CodePipeline…'
  description: 'CodePipeline

    Overview


    This is the CodePipeline API Reference.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codepipeline
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codepipeline-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: https://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: http://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
- url: https://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodePipeline 20150709.PutJobSuccessResult'
paths:
  /#X-Amz-Target=CodePipeline_20150709.PutJobSuccessResult:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PutJobSuccessResult
      description: Represents the success of a job as returned to the pipeline by a job worker. Used for custom actions only.
      responses:
        '200':
          description: Success
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                PutJobSuccessResult480Example:
                  summary: Default PutJobSuccessResult 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: JobNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobNotFoundException'
              examples:
                PutJobSuccessResult481Example:
                  summary: Default PutJobSuccessResult 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InvalidJobStateException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidJobStateException'
              examples:
                PutJobSuccessResult482Example:
                  summary: Default PutJobSuccessResult 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: OutputVariablesSizeExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputVariablesSizeExceededException'
              examples:
                PutJobSuccessResult483Example:
                  summary: Default PutJobSuccessResult 483 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutJobSuccessResultInput'
            examples:
              PutJobSuccessResultRequestExample:
                summary: Default PutJobSuccessResult request
                x-microcks-default: true
                value:
                  jobId: '500123'
                  currentRevision: example-value
                  continuationToken: example-value
                  executionDetails: example-value
                  outputVariables: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodePipeline_20150709.PutJobSuccessResult
      summary: Amazon CodePipeline Put Job Success Result
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodePipeline 20150709.PutJobSuccessResult'
components:
  schemas:
    CurrentRevision:
      type: object
      required:
      - revision
      - changeIdentifier
      properties:
        revision:
          allOf:
          - $ref: '#/components/schemas/Revision'
          - description: The revision ID of the current version of an artifact.
        changeIdentifier:
          allOf:
          - $ref: '#/components/schemas/RevisionChangeIdentifier'
          - description: The change identifier for the current revision.
        created:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: The date and time when the most recent revision of the artifact was created, in timestamp format.
        revisionSummary:
          allOf:
          - $ref: '#/components/schemas/RevisionSummary'
          - description: The summary of the most recent revision of the artifact.
      description: Represents information about a current revision.
    ExecutionDetails:
      type: object
      properties:
        summary:
          allOf:
          - $ref: '#/components/schemas/ExecutionSummary'
          - description: The summary of the current status of the actions.
        externalExecutionId:
          allOf:
          - $ref: '#/components/schemas/ExecutionId'
          - description: The system-generated unique ID of this action used to identify this job worker in any external systems, such as CodeDeploy.
        percentComplete:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The percentage of work completed on the action, represented on a scale of 0 to 100 percent.
      description: The details of the actions taken and results produced on an artifact as it passes through stages in the pipeline.
    ExecutionSummary:
      type: string
      minLength: 1
      maxLength: 2048
    OutputVariablesSizeExceededException: {}
    RevisionChangeIdentifier:
      type: string
      minLength: 1
      maxLength: 100
    ValidationException: {}
    OutputVariablesValue:
      type: string
    JobId:
      type: string
      pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    InvalidJobStateException: {}
    JobNotFoundException: {}
    ExecutionId:
      type: string
      minLength: 1
      maxLength: 1500
    Time:
      type: string
      format: date-time
    Revision:
      type: string
      minLength: 1
      maxLength: 1500
    ContinuationToken:
      type: string
      minLength: 1
      maxLength: 2048
    Percentage:
      type: integer
      minimum: 0
      maximum: 100
    PutJobSuccessResultInput:
      type: object
      required:
      - jobId
      title: PutJobSuccessResultInput
      properties:
        jobId:
          allOf:
          - $ref: '#/components/schemas/JobId'
          - description: The unique system-generated ID of the job that succeeded. This is the same ID returned from <code>PollForJobs</code>.
        currentRevision:
          allOf:
          - $ref: '#/components/schemas/CurrentRevision'
          - description: The ID of the current revision of the artifact successfully worked on by the job.
        continuationToken:
          allOf:
          - $ref: '#/components/schemas/ContinuationToken'
          - description: A token generated by a job worker, such as a CodeDeploy deployment ID, that a successful job provides to identify a custom action in progress. Future jobs use this token to identify the running instance of the action. It can be reused to return more information about the progress of the custom action. When the action is complete, no continuation token should be supplied.
        executionDetails:
          allOf:
          - $ref: '#/components/schemas/ExecutionDetails'
          - description: The execution details of the successful job, such as the actions taken by the job worker.
        outputVariables:
          allOf:
          - $ref: '#/components/schemas/OutputVariablesMap'
          - description: Key-value pairs produced as output by a job worker that can be made available to a downstream action configuration. <code>outputVariables</code> can be included only when there is no continuation token on the request.
      description: Represents the input of a <code>PutJobSuccessResult</code> action.
    RevisionSummary:
      type: string
      minLength: 1
      maxLength: 2048
    OutputVariablesMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/OutputVariablesValue'
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codepipeline/
x-hasEquivalentPaths: true
