openapi: 3.2.0
info:
  version: '2015-07-09'
  x-release: v4
  title: 'AWS CodePipeline #X Amz Target=CodePipeline…'
  description: 'CodePipeline

    Overview


    This is the CodePipeline API Reference.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codepipeline
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codepipeline-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: https://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: http://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
- url: https://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodePipeline 20150709.DeleteCustomActionType'
paths:
  /#X-Amz-Target=CodePipeline_20150709.DeleteCustomActionType:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DeleteCustomActionType
      description: 'Marks a custom action as deleted. PollForJobs for the custom action fails after the action is marked for deletion. Used for custom actions only.


        To re-create a custom action after it has been deleted you must use a string in the version field that has never been used before. This string can be an incremented version number, for example. To restore a deleted custom action, use a JSON file that is identical to the deleted action, including the original string in the version field.'
      responses:
        '200':
          description: Success
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                DeleteCustomActionType480Example:
                  summary: Default DeleteCustomActionType 480 response
                  x-microcks-default: true
                  value: STANDARD
        '481':
          description: ConcurrentModificationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrentModificationException'
              examples:
                DeleteCustomActionType481Example:
                  summary: Default DeleteCustomActionType 481 response
                  x-microcks-default: true
                  value: STANDARD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteCustomActionTypeInput'
            examples:
              DeleteCustomActionTypeRequestExample:
                summary: Default DeleteCustomActionType request
                x-microcks-default: true
                value:
                  category: example-value
                  provider: '500123'
                  version: 1.0.0
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodePipeline_20150709.DeleteCustomActionType
      summary: Amazon CodePipeline Delete Custom Action Type
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodePipeline 20150709.DeleteCustomActionType'
components:
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  schemas:
    ActionCategory:
      type: string
      enum:
      - Source
      - Build
      - Deploy
      - Test
      - Invoke
      - Approval
    ValidationException: {}
    ConcurrentModificationException: {}
    Version:
      type: string
      pattern: '[0-9A-Za-z_-]+'
      minLength: 1
      maxLength: 9
    DeleteCustomActionTypeInput:
      type: object
      required:
      - category
      - provider
      - version
      title: DeleteCustomActionTypeInput
      properties:
        category:
          allOf:
          - $ref: '#/components/schemas/ActionCategory'
          - description: The category of the custom action that you want to delete, such as source or deploy.
        provider:
          allOf:
          - $ref: '#/components/schemas/ActionProvider'
          - description: The provider of the service used in the custom action, such as CodeDeploy.
        version:
          allOf:
          - $ref: '#/components/schemas/Version'
          - description: The version of the custom action to delete.
      description: Represents the input of a <code>DeleteCustomActionType</code> operation. The custom action will be marked as deleted.
    ActionProvider:
      type: string
      pattern: '[0-9A-Za-z_-]+'
      minLength: 1
      maxLength: 35
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codepipeline/
x-hasEquivalentPaths: true
