openapi: 3.2.0
info:
  version: '2015-07-09'
  x-release: v4
  title: 'AWS CodePipeline #X Amz Target=CodePipeline…'
  description: 'CodePipeline

    Overview


    This is the CodePipeline API Reference.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codepipeline
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codepipeline-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: https://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: http://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
- url: https://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodePipeline 20150709.PutApprovalResult'
paths:
  /#X-Amz-Target=CodePipeline_20150709.PutApprovalResult:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PutApprovalResult
      description: Provides the response to a manual approval request to CodePipeline. Valid responses include Approved and Rejected.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutApprovalResultOutput'
              examples:
                PutApprovalResult200Example:
                  summary: Default PutApprovalResult 200 response
                  x-microcks-default: true
                  value:
                    approvedAt: example-value
        '480':
          description: InvalidApprovalTokenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidApprovalTokenException'
              examples:
                PutApprovalResult480Example:
                  summary: Default PutApprovalResult 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ApprovalAlreadyCompletedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApprovalAlreadyCompletedException'
              examples:
                PutApprovalResult481Example:
                  summary: Default PutApprovalResult 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: PipelineNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineNotFoundException'
              examples:
                PutApprovalResult482Example:
                  summary: Default PutApprovalResult 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: StageNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StageNotFoundException'
              examples:
                PutApprovalResult483Example:
                  summary: Default PutApprovalResult 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ActionNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionNotFoundException'
              examples:
                PutApprovalResult484Example:
                  summary: Default PutApprovalResult 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                PutApprovalResult485Example:
                  summary: Default PutApprovalResult 485 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutApprovalResultInput'
            examples:
              PutApprovalResultRequestExample:
                summary: Default PutApprovalResult request
                x-microcks-default: true
                value:
                  pipelineName: example-resource
                  stageName: example-resource
                  actionName: example-resource
                  result: example-value
                  token: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodePipeline_20150709.PutApprovalResult
      summary: Amazon CodePipeline Put Approval Result
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodePipeline 20150709.PutApprovalResult'
components:
  schemas:
    ActionNotFoundException: {}
    ApprovalToken:
      type: string
      pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    ApprovalAlreadyCompletedException: {}
    StageNotFoundException: {}
    ValidationException: {}
    InvalidApprovalTokenException: {}
    ActionName:
      type: string
      pattern: '[A-Za-z0-9.@\-_]+'
      minLength: 1
      maxLength: 100
    ApprovalStatus:
      type: string
      enum:
      - Approved
      - Rejected
    ApprovalResult:
      type: object
      required:
      - summary
      - status
      properties:
        summary:
          allOf:
          - $ref: '#/components/schemas/ApprovalSummary'
          - description: The summary of the current status of the approval request.
        status:
          allOf:
          - $ref: '#/components/schemas/ApprovalStatus'
          - description: The response submitted by a reviewer assigned to an approval action request.
      description: Represents information about the result of an approval request.
    ApprovalSummary:
      type: string
      minLength: 0
      maxLength: 512
    PutApprovalResultOutput:
      type: object
      properties:
        approvedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The timestamp showing when the approval or rejection was submitted.
      description: Represents the output of a <code>PutApprovalResult</code> action.
    StageName:
      type: string
      pattern: '[A-Za-z0-9.@\-_]+'
      minLength: 1
      maxLength: 100
    PipelineName:
      type: string
      pattern: '[A-Za-z0-9.@\-_]+'
      minLength: 1
      maxLength: 100
    PipelineNotFoundException: {}
    Timestamp:
      type: string
      format: date-time
    PutApprovalResultInput:
      type: object
      required:
      - pipelineName
      - stageName
      - actionName
      - result
      - token
      title: PutApprovalResultInput
      properties:
        pipelineName:
          allOf:
          - $ref: '#/components/schemas/PipelineName'
          - description: 'The name of the pipeline that contains the action. '
        stageName:
          allOf:
          - $ref: '#/components/schemas/StageName'
          - description: The name of the stage that contains the action.
        actionName:
          allOf:
          - $ref: '#/components/schemas/ActionName'
          - description: The name of the action for which approval is requested.
        result:
          allOf:
          - $ref: '#/components/schemas/ApprovalResult'
          - description: Represents information about the result of the approval request.
        token:
          allOf:
          - $ref: '#/components/schemas/ApprovalToken'
          - description: The system-generated token used to identify a unique approval request. The token for each open approval request can be obtained using the <a>GetPipelineState</a> action. It is used to validate that the approval request corresponding to this token is still valid.
      description: Represents the input of a <code>PutApprovalResult</code> action.
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codepipeline/
x-hasEquivalentPaths: true
