openapi: 3.2.0
info:
  version: '2015-07-09'
  x-release: v4
  title: 'AWS CodePipeline #X Amz Target=CodePipeline…'
  description: 'CodePipeline

    Overview


    This is the CodePipeline API Reference.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codepipeline
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codepipeline-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: https://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: http://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
- url: https://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodePipeline 20150709.UntagResource'
paths:
  /#X-Amz-Target=CodePipeline_20150709.UntagResource:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: UntagResource
      description: Removes tags from an Amazon Web Services resource.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UntagResourceOutput'
              examples:
                UntagResource200Example:
                  summary: Default UntagResource 200 response
                  x-microcks-default: true
                  value: {}
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                UntagResource480Example:
                  summary: Default UntagResource 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                UntagResource481Example:
                  summary: Default UntagResource 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InvalidArnException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidArnException'
              examples:
                UntagResource482Example:
                  summary: Default UntagResource 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: InvalidTagsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidTagsException'
              examples:
                UntagResource483Example:
                  summary: Default UntagResource 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ConcurrentModificationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrentModificationException'
              examples:
                UntagResource484Example:
                  summary: Default UntagResource 484 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UntagResourceInput'
            examples:
              UntagResourceRequestExample:
                summary: Default UntagResource request
                x-microcks-default: true
                value:
                  resourceArn: arn:aws:service:us-east-1:123456789012:resource/example
                  tagKeys: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodePipeline_20150709.UntagResource
      summary: Amazon CodePipeline Untag Resource
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodePipeline 20150709.UntagResource'
components:
  schemas:
    InvalidArnException: {}
    UntagResourceInput:
      type: object
      required:
      - resourceArn
      - tagKeys
      title: UntagResourceInput
      properties:
        resourceArn:
          allOf:
          - $ref: '#/components/schemas/ResourceArn'
          - description: ' The Amazon Resource Name (ARN) of the resource to remove tags from.'
        tagKeys:
          allOf:
          - $ref: '#/components/schemas/TagKeyList'
          - description: The list of keys for the tags to be removed from the resource.
    ResourceArn:
      type: string
      pattern: arn:aws(-[\w]+)*:codepipeline:.+:[0-9]{12}:.+
    ValidationException: {}
    ConcurrentModificationException: {}
    UntagResourceOutput:
      type: object
      properties: {}
    InvalidTagsException: {}
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    ResourceNotFoundException: {}
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codepipeline/
x-hasEquivalentPaths: true
