openapi: 3.2.0
info:
  version: '2015-07-09'
  x-release: v4
  title: 'AWS CodePipeline #X Amz Target=CodePipeline…'
  description: 'CodePipeline

    Overview


    This is the CodePipeline API Reference.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codepipeline
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codepipeline-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: https://codepipeline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodePipeline multi-region endpoint
- url: http://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
- url: https://codepipeline.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodePipeline endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodePipeline 20150709.PutWebhook'
paths:
  /#X-Amz-Target=CodePipeline_20150709.PutWebhook:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PutWebhook
      description: Defines a webhook and returns a unique webhook URL generated by CodePipeline. This URL can be supplied to third party source hosting providers to call every time there's a code change. When CodePipeline receives a POST request on this URL, the pipeline defined in the webhook is started as long as the POST request satisfied the authentication and filtering requirements supplied when defining the webhook. RegisterWebhookWithThirdParty and DeregisterWebhookWithThirdParty APIs can be used to automatically configure supported third parties to call the generated webhook URL.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutWebhookOutput'
              examples:
                PutWebhook200Example:
                  summary: Default PutWebhook 200 response
                  x-microcks-default: true
                  value:
                    webhook: example-value
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                PutWebhook480Example:
                  summary: Default PutWebhook 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitExceededException'
              examples:
                PutWebhook481Example:
                  summary: Default PutWebhook 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InvalidWebhookFilterPatternException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidWebhookFilterPatternException'
              examples:
                PutWebhook482Example:
                  summary: Default PutWebhook 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: InvalidWebhookAuthenticationParametersException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidWebhookAuthenticationParametersException'
              examples:
                PutWebhook483Example:
                  summary: Default PutWebhook 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: PipelineNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineNotFoundException'
              examples:
                PutWebhook484Example:
                  summary: Default PutWebhook 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: TooManyTagsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyTagsException'
              examples:
                PutWebhook485Example:
                  summary: Default PutWebhook 485 response
                  x-microcks-default: true
                  value: example-value
        '486':
          description: InvalidTagsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidTagsException'
              examples:
                PutWebhook486Example:
                  summary: Default PutWebhook 486 response
                  x-microcks-default: true
                  value: example-value
        '487':
          description: ConcurrentModificationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrentModificationException'
              examples:
                PutWebhook487Example:
                  summary: Default PutWebhook 487 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutWebhookInput'
            examples:
              PutWebhookRequestExample:
                summary: Default PutWebhook request
                x-microcks-default: true
                value:
                  webhook: example-value
                  tags: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodePipeline_20150709.PutWebhook
      summary: Amazon CodePipeline Put Webhook
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodePipeline 20150709.PutWebhook'
components:
  schemas:
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    PutWebhookInput:
      type: object
      required:
      - webhook
      title: PutWebhookInput
      properties:
        webhook:
          allOf:
          - $ref: '#/components/schemas/WebhookDefinition'
          - description: The detail provided in an input file to create the webhook, such as the webhook name, the pipeline name, and the action name. Give the webhook a unique name that helps you identify it. You might name the webhook after the pipeline and action it targets so that you can easily recognize what it's used for later.
        tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The tags for the webhook.
    TooManyTagsException: {}
    WebhookName:
      type: string
      pattern: '[A-Za-z0-9.@\-_]+'
      minLength: 1
      maxLength: 100
    WebhookAuthenticationType:
      type: string
      enum:
      - GITHUB_HMAC
      - IP
      - UNAUTHENTICATED
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    WebhookDefinition:
      type: object
      required:
      - name
      - targetPipeline
      - targetAction
      - filters
      - authentication
      - authenticationConfiguration
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/WebhookName'
          - description: The name of the webhook.
        targetPipeline:
          allOf:
          - $ref: '#/components/schemas/PipelineName'
          - description: The name of the pipeline you want to connect to the webhook.
        targetAction:
          allOf:
          - $ref: '#/components/schemas/ActionName'
          - description: The name of the action in a pipeline you want to connect to the webhook. The action must be from the source (first) stage of the pipeline.
        filters:
          allOf:
          - $ref: '#/components/schemas/WebhookFilters'
          - description: A list of rules applied to the body/payload sent in the POST request to a webhook URL. All defined rules must pass for the request to be accepted and the pipeline started.
        authentication:
          allOf:
          - $ref: '#/components/schemas/WebhookAuthenticationType'
          - description: <p>Supported options are GITHUB_HMAC, IP, and UNAUTHENTICATED.</p> <ul> <li> <p>For information about the authentication scheme implemented by GITHUB_HMAC, see <a href="https://developer.github.com/webhooks/securing/">Securing your webhooks</a> on the GitHub Developer website.</p> </li> <li> <p> IP rejects webhooks trigger requests unless they originate from an IP address in the IP range whitelisted in the authentication configuration.</p> </li> <li> <p> UNAUTHENTICATED accepts all webhook trigger requests regardless of origin.</p> </li> </ul>
        authenticationConfiguration:
          allOf:
          - $ref: '#/components/schemas/WebhookAuthConfiguration'
          - description: Properties that configure the authentication applied to incoming webhook trigger requests. The required properties depend on the authentication type. For GITHUB_HMAC, only the <code>SecretToken </code>property must be set. For IP, only the <code>AllowedIPRange </code>property must be set to a valid CIDR range. For UNAUTHENTICATED, no properties can be set.
      description: Represents information about a webhook and its definition.
    ValidationException: {}
    WebhookErrorCode:
      type: string
    ActionName:
      type: string
      pattern: '[A-Za-z0-9.@\-_]+'
      minLength: 1
      maxLength: 100
    InvalidTagsException: {}
    WebhookLastTriggered:
      type: string
      format: date-time
    WebhookArn:
      type: string
    WebhookUrl:
      type: string
      minLength: 1
      maxLength: 1000
    WebhookAuthConfigurationAllowedIPRange:
      type: string
      minLength: 1
      maxLength: 100
    WebhookErrorMessage:
      type: string
    ListWebhookItem:
      type: object
      required:
      - definition
      - url
      properties:
        definition:
          allOf:
          - $ref: '#/components/schemas/WebhookDefinition'
          - description: The detail returned for each webhook, such as the webhook authentication type and filter rules.
        url:
          allOf:
          - $ref: '#/components/schemas/WebhookUrl'
          - description: A unique URL generated by CodePipeline. When a POST request is made to this URL, the defined pipeline is started as long as the body of the post request satisfies the defined authentication and filtering conditions. Deleting and re-creating a webhook makes the old URL invalid and generates a new one.
        errorMessage:
          allOf:
          - $ref: '#/components/schemas/WebhookErrorMessage'
          - description: The text of the error message about the webhook.
        errorCode:
          allOf:
          - $ref: '#/components/schemas/WebhookErrorCode'
          - description: The number code of the error.
        lastTriggered:
          allOf:
          - $ref: '#/components/schemas/WebhookLastTriggered'
          - description: The date and time a webhook was last successfully triggered, in timestamp format.
        arn:
          allOf:
          - $ref: '#/components/schemas/WebhookArn'
          - description: The Amazon Resource Name (ARN) of the webhook.
        tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: Specifies the tags applied to the webhook.
      description: The detail returned for each webhook after listing webhooks, such as the webhook URL, the webhook name, and the webhook ARN.
    WebhookFilters:
      type: array
      items:
        $ref: '#/components/schemas/WebhookFilterRule'
      maxItems: 5
    MatchEquals:
      type: string
      minLength: 1
      maxLength: 150
    InvalidWebhookFilterPatternException: {}
    PipelineName:
      type: string
      pattern: '[A-Za-z0-9.@\-_]+'
      minLength: 1
      maxLength: 100
    JsonPath:
      type: string
      minLength: 1
      maxLength: 150
    Tag:
      type: object
      required:
      - key
      - value
      properties:
        key:
          allOf:
          - $ref: '#/components/schemas/TagKey'
          - description: The tag's key.
        value:
          allOf:
          - $ref: '#/components/schemas/TagValue'
          - description: The tag's value.
      description: A tag is a key-value pair that is used to manage the resource.
    WebhookAuthConfiguration:
      type: object
      properties:
        AllowedIPRange:
          allOf:
          - $ref: '#/components/schemas/WebhookAuthConfigurationAllowedIPRange'
          - description: The property used to configure acceptance of webhooks in an IP address range. For IP, only the <code>AllowedIPRange</code> property must be set. This property must be set to a valid CIDR range.
        SecretToken:
          allOf:
          - $ref: '#/components/schemas/WebhookAuthConfigurationSecretToken'
          - description: The property used to configure GitHub authentication. For GITHUB_HMAC, only the <code>SecretToken</code> property must be set.
      description: The authentication applied to incoming webhook trigger requests.
    ConcurrentModificationException: {}
    PipelineNotFoundException: {}
    WebhookAuthConfigurationSecretToken:
      type: string
      minLength: 1
      maxLength: 100
    PutWebhookOutput:
      type: object
      properties:
        webhook:
          allOf:
          - $ref: '#/components/schemas/ListWebhookItem'
          - description: The detail returned from creating the webhook, such as the webhook name, webhook URL, and webhook ARN.
    InvalidWebhookAuthenticationParametersException: {}
    LimitExceededException: {}
    WebhookFilterRule:
      type: object
      required:
      - jsonPath
      properties:
        jsonPath:
          allOf:
          - $ref: '#/components/schemas/JsonPath'
          - description: A JsonPath expression that is applied to the body/payload of the webhook. The value selected by the JsonPath expression must match the value specified in the <code>MatchEquals</code> field. Otherwise, the request is ignored. For more information, see <a href="https://github.com/json-path/JsonPath">Java JsonPath implementation</a> in GitHub.
        matchEquals:
          allOf:
          - $ref: '#/components/schemas/MatchEquals'
          - description: The value selected by the <code>JsonPath</code> expression must match what is supplied in the <code>MatchEquals</code> field. Otherwise, the request is ignored. Properties from the target action configuration can be included as placeholders in this value by surrounding the action configuration key with curly brackets. For example, if the value supplied here is "refs/heads/{Branch}" and the target action has an action configuration property called "Branch" with a value of "main", the <code>MatchEquals</code> value is evaluated as "refs/heads/main". For a list of action configuration properties for built-in action types, see <a href="https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements">Pipeline Structure Reference Action Requirements</a>.
      description: The event criteria that specify when a webhook notification is sent to your URL.
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codepipeline/
x-hasEquivalentPaths: true
